package com.dbmigrationqualitychecker.report;

public enum ReportType {
    RANDOM_DATA_COMPARISON,
    ALL_DATA_COMPARISON,
    COLUMN_NAME_COMPARISON,
    TABLE_ROW_COUNT_COMPARISON,
    COLUMN_METADATA_COMPARISON,
    INDEX_COMPARISON,
    RANDOM_DATA_FOR_TRANSACTION,
    RANDOM_DATA_FOR_TRANSACTION_EVENT
}
