datasource:
  source:
    type: ${SOURCE_TYPE:DB2}
    jdbc-url: ${SOURCE_JDBC_URL:jdbc:db2://localhost:50000/SOURCEDB}
    username: ${SOURCE_USERNAME:db2user}
    password: ${SOURCE_PASSWORD:changeme}
  target:
    type: ${TARGET_TYPE:MYSQL}
    jdbc-url: ${TARGET_JDBC_URL:jdbc:mysql://localhost:3306/TARGETDB}
    username: ${TARGET_USERNAME:mysqluser}
    password: ${TARGET_PASSWORD:changeme}

config:
  only-row-count: ${ONLY_RUN_ROW_COUNT:false}
  only-random-data: ${ONLY_RANDOM_DATA:false}
  only-column-metadata: ${ONLY_COLUMN_METADATA:false}
  random-data-count: ${RANDOM_DATA_COUNT:10000}

is-injected-table-file: ${IS_INJECTED_TABLE_FILE_ACTIVE:false}
